[package]
name = "sparkplane-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
serde.workspace = true
ulid.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sd-notify = "0.5"

[dev-dependencies]
serde_json.workspace = true
tokio.workspace = true
